### ISSUE TITLE
Undue collision due to URDF meshes placement

### ISSUE THREAD

**Issue by thibnoel** [open-dynamic-robot-initiative/robot_properties_solo#19]
Hello, 
I recently started working on the SOLO-12 model, especially on the characterization of the collisions. For now I only looked at the collision pair between the front left leg and the body (base link). I'm working with the FCL library to check the distance between the meshes in order to build a collision map in the shoulder's rotations space. My problem is that there is a subspace of the configuration space where the collision looks wrong (see attached pictures) : FCL detects a collision when there should not be one on the real robot in the same configuration.

![problematic_collision_view0](https://user-images.githubusercontent.com/43820910/80380791-575bcb80-88a0-11ea-9212-17919c0a6982.png)
![problematic_collision_view1](https://user-images.githubusercontent.com/43820910/80380831-63e02400-88a0-11ea-830b-cda2bfe03c9b.png)

Here as you can see, the collision that is detected is between the edge of the motor and the edge of the base link.
This problematic configuration is not unique and the subspace where it happens can be (I hope) better seen here, along with a more complete view of the collision map for the whole configuration space
![collision_config_space](https://user-images.githubusercontent.com/43820910/80381607-77d85580-88a1-11ea-9d53-3fe51ad3a1c5.png) 
![zoom_problematic_config](https://user-images.githubusercontent.com/43820910/80380844-6773ab00-88a0-11ea-9e2c-e3c54bfca9d4.png)

PS : please tell me if this issue doesnt fit the standards for this repo

**Comment by fgrimminger** [comment]
Hi - thanks for pointing this out.
There was a mistake in one of the dimensions of the simplified robot base model.
This should be fixed now.
Best. Felix

https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/quadruped_robot_12dof_v1/stl_files_for_visualization/solo_12_base.STL

**Comment by jviereck** [comment]
Hi folks,
thanks @thibnoel for reporting and @fgrimminger for providing an updated STL!

@thibnoel: Can you try to import the fixed solo_12_base.STL file from the open_robot_actuator_hardware repo into the robot_properties_solo repo and check if the collisions disappear?

Best,
Julian

**Comment by thibnoel** [comment]
Hello, thanks for the quick answer!
I tried the updated stl model for the base and it looks like the fix is working perfectly, the faulty collision is gone (figure attached)
![fixed_problematic_collision_view0](https://user-images.githubusercontent.com/43820910/80476625-ed4c3080-894a-11ea-91eb-e8b7fac5f9ce.png)

Thanks a lot again
Best, 
Thibault

**Comment by thomasfla** [comment]
Thanks @fgrimminger !
@thibnoel I don't think this issue should be closed yet since we have to update the STL here first.. Could you do a PR if you validated the new stl?

**Comment by thibnoel** [comment]
Yes you're right, I submitted the PR

**Comment by jviereck** [comment]
Thanks @thibnoel .
