### ISSUE TITLE
urdf files for the robot model

### ISSUE THREAD

**Issue by JaehyunShim** [open-dynamic-robot-initiative/robot_properties_solo#32]
Hi, 

I wonder if there are any available URDF files of this robot model for ROS users. 

Thank you in advance,
Jaehyun

**Comment by jviereck** [comment]
Hi @JaehyunShim ,

you find pregenerated URDF files here: https://github.com/open-dynamic-robot-initiative/robot_properties_solo/tree/master/src/robot_properties_solo/robot_properties_solo/pre_generated_urdf

Best,
Julian

**Comment by JaehyunShim** [comment]
@jviereck Thank you for your reply. This [webpage](https://open-dynamic-robot-initiative.github.io) says all the hardware resources for the robot are provided. Is there any URDF file for it? 

Thank you,
Jaehyun

**Comment by JaehyunShim** [comment]
Thank you very much.
