### ISSUE TITLE
Collision assessment in URDF

### ISSUE THREAD

**Issue by MusubaPy** [open-dynamic-robot-initiative/robot_properties_solo#49]
Hello, Thank you for a great project!

I am using the RaiSim simulator for reinforcement learning. The simulator only supports _URDF_ models.
I found the _XACRO_ builder and it references the _STL_ model for collision estimation.

Do you have pre generated _urdf_ files with an explicit indication of collisions like:

```
<collision>
      <origin rpy="0 1.57079632679 0" xyz="0 0 -0.125"/>
      <geometry>
        <box size="0.25 0.034 0.043"/>
      </geometry>
</collision>
```

Or urdf file with links to _.obj_ files?

**Comment by michel-aractingi** [comment]
Hi,

I modified the original solo urdf to change collisions from meshes to boxes. 
You need to transform the STL files to OBJ.

[solo.urdf.txt](https://github.com/open-dynamic-robot-initiative/robot_properties_solo/files/7803935/solo.urdf.txt)

I hope this helps.
